language: php
php:
- '7.1'

install:
- composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
- mkdir -p drupal/web/modules/${PWD##*/} && cp -a ${PWD##*/}* tests src drupal/web/modules/${PWD##*/}
script:
- drupal/vendor/bin/phpunit -c drupal/web/core drupal/web/modules/${PWD##*/}/tests/ --coverage-clover clover.xml --log-junit junit.log
